---
title: "statlearning-final"
author: "Horatiu"
date: '2022-07-13'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

FIFA 22
first we do libraries

```{r}
library(knitr) 
#library(kableExtra) #nice html tables
#library(magick)     #working with images
library(ggplot2)    #graphs
library(reshape2)   #dataframe reshaping
library(viridis)    #colors
library(stringr)    #working with strings
library(FactoMineR) #factor analysis (PCA)
library(factoextra) #factor analysis (PCA)
#library(kohonen)    #self-organised maps/SOM 
# libraries
library(dplyr)
library(ggplot2)
library(MASS)
#library(randomForest)
library(class)
#library(caret)
library(corrplot)
library(gridExtra)
install.packages("caret")
library(mlbench)
library(caret)
```

## Data Cleaning


```{r}
players_full <- read.csv(file = 'E:/horatiu/FIS/players_22.csv/players_22.csv') #full dataset
dim(players_full)
#summary(players_full)
```

```{r}
players_22 <- subset(players_full, select = c("short_name","club_position","age","height_cm","weight_kg","pace","shooting","passing","dribbling","defending","physic","attacking_crossing","attacking_finishing","attacking_heading_accuracy","attacking_short_passing","attacking_volleys","skill_dribbling","skill_curve","skill_fk_accuracy","skill_long_passing","skill_ball_control","movement_acceleration","movement_sprint_speed","movement_agility","movement_reactions","movement_balance","power_shot_power","power_jumping","power_stamina","power_strength","power_long_shots","mentality_aggression","mentality_interceptions","mentality_positioning","mentality_vision","mentality_penalties","mentality_composure","defending_marking_awareness","defending_standing_tackle","defending_sliding_tackle"))
dim(players_22)


```
```{r}
head(players_22, n=5)
summary(players_22)
```
## Check how many goalkeepers

```{r}
goalkeepers <- str_detect(players_22$club_position, "GK")
sum(goalkeepers)

```
#eliminate goalkeepers
```{r}
players_22<-subset(players_22, club_position!="GK")
which(apply(X = players_22, MARGIN = 2, FUN = anyNA) == TRUE) # check for NA
dim(players_22)
#head(players_22, n = 2)
```

```{r}
players_22 <- na.omit(players_22) # delete NA
dim(players_22)
col<-colnames(players_22)
col
```

```{r}
#we have to melt the dataset to use in ggplot

players_num = subset(players_22, select = -c(short_name,club_position))
players_num$height_cm <- players_num$height_cm - 100
players_m <- melt(players_num)
head(players_m)
cormatrix <- cor(players_num)
corrplot(cor(players_num))
players_m
```
#correlation
```{r}
highcorr <- findCorrelation(cormatrix, cutoff=0.75)
highcorr
col2<-colnames(players_num)
col2<-col2[-highcorr]

corrplot(cor(players_num[col2])) # it looks much better so we use the variables from col 2
col2[18]<- "club_position"
col2
players_model <- subset(players_22, select = c(col2))

```


```{r}
col[highcorr]
#vizualizing positions
unique(players_22$club_position)
```

```{r}
#here we do the cool violin plots to check distributions
p <- ggplot(data = players_m, aes(y = variable, x = value, fill = variable, alpha = 0.7)) + 
             geom_boxplot() + geom_violin() + scale_fill_manual(values = viridis(45)) + guides(fill = "none")
p
```
#one-hot encoding for classification
```{r}
players.pca<-prcomp(players_num,center=TRUE, scale.=TRUE)
summary(players.pca)
players.pca
fviz_eig(players.pca, addlabels = TRUE)
```

```{r}
fviz_pca_var(players.pca, labelsize = 2, alpha.var = 1.0, title = "Factor Plane for the FIFA 22 Data")
```

### train-test split

```{r}
## 70% of the sample size
smp_size <- floor(0.7 * nrow(players_model))

## set the seed to make your partition reproducible
set.seed(123)
train_ind <- sample(seq_len(nrow(players_model)), size = smp_size)

train <- players_model[train_ind, ]
test <- players_model[-train_ind, ]
dim(test)
```