---
title: "Untitled"
author: "Horatiu"
date: '2022-06-22'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

FIFA 22
first we do libraries

```{r}
library(knitr) 
#library(kableExtra) #nice html tables
#library(magick)     #working with images
library(ggplot2)    #graphs
library(reshape2)   #dataframe reshaping
library(viridis)    #colors
library(stringr)    #working with strings
library(FactoMineR) #factor analysis (PCA)
library(factoextra) #factor analysis (PCA)
#library(kohonen)    #self-organised maps/SOM 
```

## EDA


```{r}
players_full <- read.csv(file = 'E:/horatiu/FIS/players_22.csv/players_22.csv') #full dataset
dim(players_full)
summary(players_full)
```

```{r}
#head(players_full, n = 5)
players_22 <- subset(players_full, select = -c(sofifa_id,player_url,long_name,dob,club_jersey_number, club_loaned_from,club_joined,club_contract_valid_until,nationality_id,nation_team_id,nation_jersey_number,release_clause_eur,player_tags,player_traits,player_face_url,club_logo_url,club_flag_url,club_team_id,wage_eur,real_face,nation_logo_url,nation_flag_url,work_rate,goalkeeping_speed,club_jersey_number,club_team_id,nation_team_id,nation_jersey_number,release_clause_eur,club_contract_valid_until,release_clause_eur, league_level,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,ls,st,rs,lw,lf,cf,rf,rw,lam,cam,ram,lm,lcm,cm,rcm,rm,lwb,ldm,cdm,rdm,rwb,lb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk,club_name,international_reputation,nationality_name,league_name,player_positions,nation_position))
dim(players_22)


```
```{r}
head(players_22, n=5)
summary(players_22)
```
## Check for Na - many cause we have both goalkeepers and players
```{r}
which(apply(X = players_22, MARGIN = 2, FUN = anyNA) == TRUE)
```
## Check how many goalkeepers

```{r}
goalkeepers <- str_detect(players_22$player_positions, "GK")
sum(goalkeepers)
```
#separate goalkeepers
```{r}
gk_df<-subset(players_22, player_positions="GK")
players_22<-subset(players_22, club_position!="GK")
which(apply(X = players_22, MARGIN = 2, FUN = anyNA) == TRUE)
dim(players_22)
head(players_22, n = 2)
```
```{r}
players_22 <- na.omit(players_22)
dim(players_22)
col<-colnames(players_22)
col
```
# some cool plots
```{r}
#we have to melt the dataset to use in ggplot

players_num = subset(players_22, select = c("overall","potential","age","height_cm","weight_kg","skill_moves","pace","shooting","passing","dribbling","defending","physic","attacking_crossing","attacking_finishing","attacking_heading_accuracy","attacking_short_passing","attacking_volleys","skill_dribbling","skill_curve","skill_fk_accuracy","skill_long_passing","skill_ball_control","movement_acceleration","movement_sprint_speed","movement_agility","movement_reactions","movement_balance","power_shot_power","power_jumping","power_stamina","power_strength","power_long_shots","mentality_aggression","mentality_interceptions","mentality_positioning","mentality_vision","mentality_penalties","mentality_composure","defending_marking_awareness","defending_standing_tackle","defending_sliding_tackle"))
players_m <- melt(players_22,id.vars = "short_name", measure.vars =c("overall","potential","age","height_cm","weight_kg","skill_moves","pace","shooting","passing","dribbling","defending","physic","attacking_crossing","attacking_finishing","attacking_heading_accuracy","attacking_short_passing","attacking_volleys","skill_dribbling","skill_curve","skill_fk_accuracy","skill_long_passing","skill_ball_control","movement_acceleration","movement_sprint_speed","movement_agility","movement_reactions","movement_balance","power_shot_power","power_jumping","power_stamina","power_strength","power_long_shots","mentality_aggression","mentality_interceptions","mentality_positioning","mentality_vision","mentality_penalties","mentality_composure","defending_marking_awareness","defending_standing_tackle","defending_sliding_tackle")) 
head(players_m)
cormatrix <- round(cor(players_num),2)
ggplot(data = players_m, aes(x=variable, y=variable, fill=value)) + 
  geom_tile()

```

```{r}
p <- ggplot(data = players_m, aes(y = variable, x = value, fill = variable, alpha = 0.5)) + 
             geom_boxplot() + geom_violin() + scale_fill_manual(values = viridis(45)) + guides(fill = "none")
p
```
